#!/usr/bin/env python3
from pathlib import Path
import base64
ROOT=Path.cwd()
path=ROOT/'scripts/sync-matches.mjs'
if not path.exists(): raise SystemExit('scripts/sync-matches.mjs introuvable : lance ce script depuis la racine du dépôt.')
content=path.read_text(encoding='utf-8')

old=base64.b64decode('Y29uc3QgU1lOQ19WRVJTSU9OPScyMDI2LjEwLjAxLXN0YW5kaW5ncy0zMScsQ0xVQl9OTz0nMTAxNTQ0JyxDTFVCX0NPREU9JzU1MDM1MCcsRElTVFJJQ1RfTk89Jzg2Jzs=').decode('utf-8')
new=base64.b64decode('Y29uc3QgU1lOQ19WRVJTSU9OPScyMDI2LjEwLjAxLXN0YW5kaW5ncy0zMicsQ0xVQl9OTz0nMTAxNTQ0JyxDTFVCX0NPREU9JzU1MDM1MCcsRElTVFJJQ1RfTk89Jzg2Jzs=').decode('utf-8')
label='version v32'
if new not in content:
    if old not in content: raise SystemExit(f'Motif introuvable : {label}')
    content=content.replace(old,new,1)

old=base64.b64decode('Y29uc3QgcmV0cnlhYmxlPXN0YXR1cz0+WzQyOSw1MDAsNTAyLDUwMyw1MDRdLmluY2x1ZGVzKE51bWJlcihzdGF0dXMpKTs=').decode('utf-8')
new=base64.b64decode('Y29uc3QgcmV0cnlhYmxlPXN0YXR1cz0+WzAsNDI5LDUwMCw1MDIsNTAzLDUwNF0uaW5jbHVkZXMoTnVtYmVyKHN0YXR1cykpOw==').decode('utf-8')
label='retry erreurs réseau'
if new not in content:
    if old not in content: raise SystemExit(f'Motif introuvable : {label}')
    content=content.replace(old,new,1)

old=base64.b64decode('ICBjb25zdCBmYWxHYW1lUGF5bG9hZHM9ZW1iZWRkZWRFbnRyaWVzQnlQcmVmaXgoaHRtbCwnZmNlLWZhbC1nYW1lcy0nKTsKICBjb25zdCBzdGFuZGluZ3M9ZW1iZWRkZWRQYXlsb2FkRnJvbUh0bWwoaHRtbCwnZmNlLXN0YW5kaW5ncycpfHxbXTsK').decode('utf-8')
new=base64.b64decode('ICBjb25zdCBmYWxHYW1lUGF5bG9hZHM9ZW1iZWRkZWRFbnRyaWVzQnlQcmVmaXgoaHRtbCwnZmNlLWZhbC1nYW1lcy0nKTsKICBjb25zdCBmYWxHYW1lTWV0YT1lbWJlZGRlZFBheWxvYWRGcm9tSHRtbChodG1sLCdmY2UtcGxhdGVhdS1kZXRhaWwtbWV0YScpfHx7fTsKICBjb25zdCBzdGFuZGluZ3M9ZW1iZWRkZWRQYXlsb2FkRnJvbUh0bWwoaHRtbCwnZmNlLXN0YW5kaW5ncycpfHxbXTsK').decode('utf-8')
label='lecture meta détails plateaux'
if new not in content:
    if old not in content: raise SystemExit(f'Motif introuvable : {label}')
    content=content.replace(old,new,1)

old=base64.b64decode('ICAgIGZhbEdhbWVQYXlsb2FkcywKICAgIHN0YW5kaW5ncywK').decode('utf-8')
new=base64.b64decode('ICAgIGZhbEdhbWVQYXlsb2FkcywKICAgIGZhbEdhbWVNZXRhLAogICAgc3RhbmRpbmdzLAo=').decode('utf-8')
label='retour meta détails plateaux'
if new not in content:
    if old not in content: raise SystemExit(f'Motif introuvable : {label}')
    content=content.replace(old,new,1)

old=base64.b64decode('ICAgIGNvbnN0IGZldGNoUGxhdGVhdT1hc3luYyh7a2V5LHVybH0pPT57CiAgICAgIGxldCBzdGF0dXM9MCxib2R5PScnOwogICAgICB0cnl7CiAgICAgICAgY29uc3QgcmVzcG9uc2U9YXdhaXQgZmV0Y2godXJsLHtjcmVkZW50aWFsczonaW5jbHVkZScsaGVhZGVyczp7QWNjZXB0Oid0ZXh0L2h0bWwsYXBwbGljYXRpb24veGh0bWwreG1sJ319KTsKICAgICAgICBzdGF0dXM9cmVzcG9uc2Uuc3RhdHVzOwogICAgICAgIGNvbnN0IGh0bWw9YXdhaXQgcmVzcG9uc2UudGV4dCgpOwogICAgICAgIGNvbnN0IHN0YXRlVGV4dD1odG1sLm1hdGNoKC88c2NyaXB0W14+XStpZD1bIiddbmctc3RhdGVbIiddW14+XSo+KFtcXHNcXFNdKj8pPFxcL3NjcmlwdD4vaSk/LlsxXXx8Jyc7CiAgICAgICAgY29uc3Qgc3RhdGU9c3RhdGVUZXh0P0pTT04ucGFyc2Uoc3RhdGVUZXh0KTpbXTsKICAgICAgICBjb25zdCBlbnRyaWVzPShBcnJheS5pc0FycmF5KHN0YXRlKT9zdGF0ZTpbc3RhdGVdKS5mbGF0TWFwKGl0ZW09Pk9iamVjdC5lbnRyaWVzKGl0ZW18fHt9KSk7CiAgICAgICAgY29uc3QgYXBpUGF5bG9hZHM9ZW50cmllcwogICAgICAgICAgLmZpbHRlcigoW25hbWUsdmFsdWVdKT0+bmFtZS5pbmNsdWRlcygnL2FwaS9mYWwvJykmJnZhbHVlPy5zdGF0dXM9PT0yMDAmJnZhbHVlPy5ib2R5KQogICAgICAgICAgLm1hcCgoW25hbWUsdmFsdWVdKT0+KHtuYW1lLGJvZHk6dmFsdWUuYm9keX0pKTsKICAgICAgICBib2R5PUpTT04uc3RyaW5naWZ5KHtzaXRlX2tleTprZXksYXBpX3BheWxvYWRzOmFwaVBheWxvYWRzfSk7CiAgICAgIH1jYXRjaChlcnJvcil7Ym9keT1KU09OLnN0cmluZ2lmeSh7c2l0ZV9rZXk6a2V5LGZjZV9lcnJvcjpTdHJpbmcoZXJyb3IpfSl9CiAgICAgIGNvbnN0IG91dHB1dD1kb2N1bWVudC5jcmVhdGVFbGVtZW50KCdzY3JpcHQnKTsKICAgICAgb3V0cHV0LnR5cGU9J2FwcGxpY2F0aW9uL2pzb24nO291dHB1dC5pZD1cYGZjZS1mYWwtZ2FtZXMtXCR7a2V5LnJlcGxhY2VBbGwoJzonLCctJyl9XGA7CiAgICAgIGxldCBlbnZlbG9wZUJvZHk9Ym9keTsKICAgICAgdHJ5e2VudmVsb3BlQm9keT1KU09OLnBhcnNlKGJvZHkpfWNhdGNoe30KICAgICAgb3V0cHV0LnRleHRDb250ZW50PUpTT04uc3RyaW5naWZ5KHtzdGF0dXMsYm9keTplbnZlbG9wZUJvZHl9KTtkb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKG91dHB1dCk7CiAgICB9OwogICAgYXdhaXQgUHJvbWlzZS5hbGwoWy4uLnBsYXRlYXVTaXRlcy52YWx1ZXMoKV0ubWFwKGZldGNoUGxhdGVhdSkpOwo=').decode('utf-8')
new=base64.b64decode('ICAgIGNvbnN0IHBsYXRlYXVSZXN1bHRzPVtdOwoKICAgIGNvbnN0IGZldGNoUGxhdGVhdT1hc3luYyh7a2V5LHVybH0pPT57CiAgICAgIGxldCBzdGF0dXM9MCxib2R5PScnLGF0dGVtcHQ9MDsKCiAgICAgIHdoaWxlKGF0dGVtcHQ8Mil7CiAgICAgICAgYXR0ZW1wdCsrOwoKICAgICAgICB0cnl7CiAgICAgICAgICBjb25zdCByZXNwb25zZT1hd2FpdCBmZXRjaCgKICAgICAgICAgICAgdXJsLAogICAgICAgICAgICB7CiAgICAgICAgICAgICAgY3JlZGVudGlhbHM6J2luY2x1ZGUnLAogICAgICAgICAgICAgIGhlYWRlcnM6e0FjY2VwdDondGV4dC9odG1sLGFwcGxpY2F0aW9uL3hodG1sK3htbCd9CiAgICAgICAgICAgIH0KICAgICAgICAgICk7CgogICAgICAgICAgc3RhdHVzPXJlc3BvbnNlLnN0YXR1czsKICAgICAgICAgIGNvbnN0IGh0bWw9YXdhaXQgcmVzcG9uc2UudGV4dCgpOwoKICAgICAgICAgIGlmKHJlc3BvbnNlLm9rKXsKICAgICAgICAgICAgY29uc3Qgc3RhdGVUZXh0PQogICAgICAgICAgICAgIGh0bWwubWF0Y2goCiAgICAgICAgICAgICAgICAvPHNjcmlwdFtePl0raWQ9WyInXW5nLXN0YXRlWyInXVtePl0qPihbXFxzXFxTXSo/KTxcXC9zY3JpcHQ+L2kKICAgICAgICAgICAgICApPy5bMV0KICAgICAgICAgICAgICB8fCcnOwoKICAgICAgICAgICAgY29uc3Qgc3RhdGU9CiAgICAgICAgICAgICAgc3RhdGVUZXh0CiAgICAgICAgICAgICAgICA/SlNPTi5wYXJzZShzdGF0ZVRleHQpCiAgICAgICAgICAgICAgICA6W107CgogICAgICAgICAgICBjb25zdCBlbnRyaWVzPQogICAgICAgICAgICAgIChBcnJheS5pc0FycmF5KHN0YXRlKT9zdGF0ZTpbc3RhdGVdKQogICAgICAgICAgICAgICAgLmZsYXRNYXAoaXRlbT0+T2JqZWN0LmVudHJpZXMoaXRlbXx8e30pKTsKCiAgICAgICAgICAgIGNvbnN0IGFwaVBheWxvYWRzPQogICAgICAgICAgICAgIGVudHJpZXMKICAgICAgICAgICAgICAgIC5maWx0ZXIoCiAgICAgICAgICAgICAgICAgIChbbmFtZSx2YWx1ZV0pPT4KICAgICAgICAgICAgICAgICAgICBuYW1lLmluY2x1ZGVzKCcvYXBpL2ZhbC8nKQogICAgICAgICAgICAgICAgICAgICYmdmFsdWU/LnN0YXR1cz09PTIwMAogICAgICAgICAgICAgICAgICAgICYmdmFsdWU/LmJvZHkKICAgICAgICAgICAgICAgICkKICAgICAgICAgICAgICAgIC5tYXAoCiAgICAgICAgICAgICAgICAgIChbbmFtZSx2YWx1ZV0pPT4oewogICAgICAgICAgICAgICAgICAgIG5hbWUsCiAgICAgICAgICAgICAgICAgICAgYm9keTp2YWx1ZS5ib2R5CiAgICAgICAgICAgICAgICAgIH0pCiAgICAgICAgICAgICAgICApOwoKICAgICAgICAgICAgYm9keT1KU09OLnN0cmluZ2lmeSh7CiAgICAgICAgICAgICAgc2l0ZV9rZXk6a2V5LAogICAgICAgICAgICAgIGFwaV9wYXlsb2FkczphcGlQYXlsb2FkcwogICAgICAgICAgICB9KTsKCiAgICAgICAgICAgIGJyZWFrOwogICAgICAgICAgfQoKICAgICAgICAgIGJvZHk9SlNPTi5zdHJpbmdpZnkoewogICAgICAgICAgICBzaXRlX2tleTprZXksCiAgICAgICAgICAgIGZjZV9lcnJvcjpgSFRUUCAke3N0YXR1c31gCiAgICAgICAgICB9KTsKCiAgICAgICAgfWNhdGNoKGVycm9yKXsKICAgICAgICAgIHN0YXR1cz0wOwogICAgICAgICAgYm9keT1KU09OLnN0cmluZ2lmeSh7CiAgICAgICAgICAgIHNpdGVfa2V5OmtleSwKICAgICAgICAgICAgZmNlX2Vycm9yOlN0cmluZyhlcnJvcikKICAgICAgICAgIH0pOwogICAgICAgIH0KCiAgICAgICAgaWYoYXR0ZW1wdDwyJiZyZXRyeWFibGUoc3RhdHVzKSl7CiAgICAgICAgICBhd2FpdCBzbGVlcCg1MDAqYXR0ZW1wdCk7CiAgICAgICAgICBjb250aW51ZTsKICAgICAgICB9CgogICAgICAgIGJyZWFrOwogICAgICB9CgogICAgICBjb25zdCBvdXRwdXQ9ZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnc2NyaXB0Jyk7CiAgICAgIG91dHB1dC50eXBlPSdhcHBsaWNhdGlvbi9qc29uJzsKICAgICAgb3V0cHV0LmlkPVxgZmNlLWZhbC1nYW1lcy1cJHtrZXkucmVwbGFjZUFsbCgnOicsJy0nKX1cYDsKCiAgICAgIGxldCBlbnZlbG9wZUJvZHk9Ym9keTsKICAgICAgdHJ5e2VudmVsb3BlQm9keT1KU09OLnBhcnNlKGJvZHkpfWNhdGNoe30KCiAgICAgIG91dHB1dC50ZXh0Q29udGVudD1KU09OLnN0cmluZ2lmeSh7CiAgICAgICAgc3RhdHVzLAogICAgICAgIGJvZHk6ZW52ZWxvcGVCb2R5LAogICAgICAgIGF0dGVtcHRzOmF0dGVtcHQKICAgICAgfSk7CgogICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKG91dHB1dCk7CgogICAgICBwbGF0ZWF1UmVzdWx0cy5wdXNoKHsKICAgICAgICBrZXksCiAgICAgICAgc3RhdHVzLAogICAgICAgIGF0dGVtcHRzOmF0dGVtcHQKICAgICAgfSk7CiAgICB9OwoKICAgIGNvbnN0IHBsYXRlYXVJdGVtcz1bLi4ucGxhdGVhdVNpdGVzLnZhbHVlcygpXTsKICAgIGxldCBwbGF0ZWF1Q3Vyc29yPTA7CgogICAgY29uc3QgcGxhdGVhdVdvcmtlcj1hc3luYygpPT57CiAgICAgIHdoaWxlKHBsYXRlYXVDdXJzb3I8cGxhdGVhdUl0ZW1zLmxlbmd0aCl7CiAgICAgICAgY29uc3QgaW5kZXg9cGxhdGVhdUN1cnNvcisrOwogICAgICAgIGF3YWl0IGZldGNoUGxhdGVhdShwbGF0ZWF1SXRlbXNbaW5kZXhdKTsKICAgICAgfQogICAgfTsKCiAgICBhd2FpdCBQcm9taXNlLmFsbCgKICAgICAgQXJyYXkuZnJvbSgKICAgICAgICB7bGVuZ3RoOk1hdGgubWluKDQscGxhdGVhdUl0ZW1zLmxlbmd0aCl9LAogICAgICAgICgpPT5wbGF0ZWF1V29ya2VyKCkKICAgICAgKQogICAgKTsKCiAgICBjb25zdCBwbGF0ZWF1TWV0YU91dHB1dD1kb2N1bWVudC5jcmVhdGVFbGVtZW50KCdzY3JpcHQnKTsKICAgIHBsYXRlYXVNZXRhT3V0cHV0LnR5cGU9J2FwcGxpY2F0aW9uL2pzb24nOwogICAgcGxhdGVhdU1ldGFPdXRwdXQuaWQ9J2ZjZS1wbGF0ZWF1LWRldGFpbC1tZXRhJzsKICAgIHBsYXRlYXVNZXRhT3V0cHV0LnRleHRDb250ZW50PUpTT04uc3RyaW5naWZ5KHsKICAgICAgc3RhdHVzOjIwMCwKICAgICAgYm9keTp7CiAgICAgICAgdGFyZ2V0ZWQ6cGxhdGVhdUl0ZW1zLmxlbmd0aCwKICAgICAgICBzdWNjZWVkZWQ6cGxhdGVhdVJlc3VsdHMuZmlsdGVyKGl0ZW09Pml0ZW0uc3RhdHVzPT09MjAwKS5sZW5ndGgsCiAgICAgICAgZmFpbGVkOnBsYXRlYXVSZXN1bHRzLmZpbHRlcihpdGVtPT5pdGVtLnN0YXR1cyE9PTIwMCkKICAgICAgfQogICAgfSk7CiAgICBkb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKHBsYXRlYXVNZXRhT3V0cHV0KTsK').decode('utf-8')
label='retry détails plateaux'
if new not in content:
    if old not in content: raise SystemExit(f'Motif introuvable : {label}')
    content=content.replace(old,new,1)

old=base64.b64decode('ICBjb25zdCBwbGF0ZWF1R2FtZUNvdW50PXBheWxvYWRzLmZhbEdhbWVQYXlsb2Fkcy5yZWR1Y2UoKHRvdGFsLGVudHJ5KT0+dG90YWwrbm9ybWFsaXplRmFsR2FtZXMoZW50cnkucGF5bG9hZCkubGVuZ3RoLDApOwogIGNvbnNvbGUubG9nKGBGRkYgOiAke3BheWxvYWRzLmZhbEdhbWVQYXlsb2Fkcy5sZW5ndGh9IHBhZ2UocykgZGUgZMOpdGFpbCBkZSBwbGF0ZWF1IGNpYmzDqWUocyksICR7cGxhdGVhdUdhbWVDb3VudH0gbWluaS1tYXRjaChzKSB0cm91dsOpKHMpLCBzYW5zIGNyw6lkaXQgWmVuUm93cyBzdXBwbMOpbWVudGFpcmUuYCk7Cg==').decode('utf-8')
new=base64.b64decode('ICBjb25zdCBwbGF0ZWF1R2FtZUNvdW50PXBheWxvYWRzLmZhbEdhbWVQYXlsb2Fkcy5yZWR1Y2UoKHRvdGFsLGVudHJ5KT0+dG90YWwrbm9ybWFsaXplRmFsR2FtZXMoZW50cnkucGF5bG9hZCkubGVuZ3RoLDApOwogIGNvbnN0IHBsYXRlYXVEZXRhaWxUYXJnZXRlZD1OdW1iZXIocGF5bG9hZHMuZmFsR2FtZU1ldGE/LnRhcmdldGVkfHxwYXlsb2Fkcy5mYWxHYW1lUGF5bG9hZHMubGVuZ3RoKTsKICBjb25zdCBwbGF0ZWF1RGV0YWlsU3VjY2VlZGVkPU51bWJlcihwYXlsb2Fkcy5mYWxHYW1lTWV0YT8uc3VjY2VlZGVkfHxwYXlsb2Fkcy5mYWxHYW1lUGF5bG9hZHMubGVuZ3RoKTsKICBjb25zb2xlLmxvZygKICAgIGBGRkYgOiBkw6l0YWlscyBkZSBwbGF0ZWF1IOKAlCAke3BsYXRlYXVEZXRhaWxUYXJnZXRlZH0gY2libMOpKHMpLCBgKwogICAgYCR7cGxhdGVhdURldGFpbFN1Y2NlZWRlZH0gcsOpdXNzaShzKSwgJHtwbGF0ZWF1R2FtZUNvdW50fSBtaW5pLW1hdGNoKHMpIHRyb3V2w6kocyksIGArCiAgICBgc2FucyBjcsOpZGl0IFplblJvd3Mgc3VwcGzDqW1lbnRhaXJlLmAKICApOwogIGlmKEFycmF5LmlzQXJyYXkocGF5bG9hZHMuZmFsR2FtZU1ldGE/LmZhaWxlZCkmJnBheWxvYWRzLmZhbEdhbWVNZXRhLmZhaWxlZC5sZW5ndGgpewogICAgY29uc29sZS5sb2coCiAgICAgIGA6Ondhcm5pbmcgdGl0bGU9RMOpdGFpbHMgcGxhdGVhdXggRkZGOjpgKwogICAgICBwYXlsb2Fkcy5mYWxHYW1lTWV0YS5mYWlsZWQKICAgICAgICAubWFwKGl0ZW09PmAke2l0ZW0ua2V5fSBIVFRQICR7aXRlbS5zdGF0dXN8fCdyw6lzZWF1J30gKCR7aXRlbS5hdHRlbXB0c3x8MX0gZXNzYWkocykpYCkKICAgICAgICAuam9pbignLCAnKQogICAgKTsKICB9Cg==').decode('utf-8')
label='log détails plateaux correct'
if new not in content:
    if old not in content: raise SystemExit(f'Motif introuvable : {label}')
    content=content.replace(old,new,1)

old=base64.b64decode('ICAgICAgcGxhdGVhdV9nYW1lczpwbGF0ZWF1R2FtZXMsCiAgICAgIHJhd19qc29uOnNpdGUK').decode('utf-8')
new=base64.b64decode('ICAgICAgcGxhdGVhdV9nYW1lczoKICAgICAgICBnYW1lRGV0YWlscy5oYXMoZ2FtZURldGFpbEtleSkKICAgICAgICAgID9wbGF0ZWF1R2FtZXMKICAgICAgICAgIDp1bmRlZmluZWQsCiAgICAgIHJhd19qc29uOnNpdGUK').decode('utf-8')
label='préservation mini-matchs sur échec'
if new not in content:
    if old not in content: raise SystemExit(f'Motif introuvable : {label}')
    content=content.replace(old,new,1)

path.write_text(content,encoding='utf-8')
print('Correctif FFF v32 appliqué à scripts/sync-matches.mjs')
print('Ensuite :')
print('  node --check scripts/sync-matches.mjs')
print('  node --check scripts/standings-integrated.mjs')
print('  npm run build')
print('Puis relancer Synchroniser les matchs — préproduction.')
